### ISSUE TITLE
Trying to review pictures on Sailfish OS (Jolla) crashes Mapillary app

### ISSUE THREAD

**Issue by ltog** [mapillary/mapillary_issues#1142]
I'm running the Mapillary app on Sailfish OS Version 1.1.6.27 on the Jolla mobile phone.

I took around 250 pictures in 2 sequences. If I click one of the sequences (under the menu option "Review"), I get the message

    Unfortunately, Mapillary has stopped.

and have to reopen the app.

**Comment by jesolem** [comment]
@peterneubauer is this perhaps an old version? Maybe we need to update the Jolla version.

**Comment by peterneubauer** [comment]
Mmh, do you have a link to the download, or can submit a log via settings->send logs?

**Comment by ltog** [comment]
> Mmh, do you have a link to the download

I don't unterstand this part of the question:
- The Sailfish OS should be in its latest version since I upgraded it just recently.
- I downloaded and installed the .apk file (from the Mapillary website) of what I believe was the most current offered version of the Mapillary app.

If I click on "Send debug logs" the Feed page (or Profile page, whatever I looked at before) appears and the menu disappears, nothing else seems to happen. Is this the intended behaviour?

**Comment by peterneubauer** [comment]
Mmh,
so yes, this explains things a bit. Latest Mapillary version, and it seems the logging system is not working as in Android. Could you try to set Settings->Developer->Trace, and then send? Is that working?

**Comment by ltog** [comment]
The behaviour was the same with activated trace: After clicking "Send debug logs" the feed page reappeared.

However, I extracted the contents of the logfiles and am pasting them here:

mapillary.log (truncated):

```
--------- beginning of /dev/log/main
07-09 20:07:00.111 E/ProviderInstaller(12219): Unable to load native code from /data/data/app.mapillary/lib/libgmscore.so
07-09 20:07:00.122 E/ProviderInstaller(12219): libgmscore version mismatch (0 vs. 7329)
07-09 20:10:06.840 E/ProviderInstaller(13710): Unable to load native code from /data/data/app.mapillary/lib/libgmscore.so
07-09 20:10:06.846 E/ProviderInstaller(13710): libgmscore version mismatch (0 vs. 7329)
07-09 20:10:34.685 E/AndroidRuntime(13710): FATAL EXCEPTION: main
07-09 20:10:34.685 E/AndroidRuntime(13710): java.lang.NoSuchMethodError: app.mapillary.android.activity.ReviewSequenceActivity.getDrawable
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at app.mapillary.android.activity.ReviewSequenceActivity$SequenceReviewArrayListAdapter.getView(ReviewSequenceActivity.java:315)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.AbsListView.obtainView(AbsListView.java:2271)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.GridView.onMeasure(GridView.java:1030)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.View.measure(View.java:15198)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.View.measure(View.java:15198)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.View.measure(View.java:15198)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.View.measure(View.java:15198)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2148)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.View.measure(View.java:15198)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1853)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1103)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1278)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1001)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4218)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.Choreographer.doFrame(Choreographer.java:525)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.os.Handler.handleCallback(Handler.java:615)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.os.Handler.dispatchMessage(Handler.java:92)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.os.Looper.loop(Looper.java:137)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at android.app.ActivityThread.main(ActivityThread.java:4781)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at java.lang.reflect.Method.invoke(Method.java:511)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
07-09 20:10:34.685 E/AndroidRuntime(13710): 	at dalvik.system.NativeStart.main(Native Method)
07-09 20:10:40.042 E/ProviderInstaller(13889): Unable to load native code from /data/data/app.mapillary/lib/libgmscore.so
07-09 20:10:40.052 E/ProviderInstaller(13889): libgmscore version mismatch (0 vs. 7329)
```


mapillary_trace.txt (truncated):

```
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - Android version: 16
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - OS version: 3.4.106.20150416.1
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - Device alien_jolla_bionic
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - Model Jolla
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - Product alien_jolla_bionic
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - Mapillary versionName: 1.28
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.MainActivity  - Mapillary versionCode: 128
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.service.MapillaryServerFacade  - getHttpPost: https://a.mapillary.com/v2/ua/login?client_id=MkJKbDA0bnZuZlcxeTJHTmFqN3g1dzo0ZmYxN2MzMTRlYzM1M2E2
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - found: /firmware
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - found: /mnt/asec
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - found: /mnt/obb
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - found: /home/nemo/android_storage
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - def_path /home/nemo/android_storage/Pictures, def_path_internal true, def_path_readonly false
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - ExternalStorageDir: /home/nemo/android_storage
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - mount found: /home/nemo/android_storage/Pictures
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - mount found: /home/nemo/android_storage
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - Mounted external StorageDir found, path: /home/nemo/android_storage
Thu Jul 09 19:51:46 CEST 2015 : app.mapillary.android.activity.StorageUtils  - bestPath: /home/nemo/android_storage/mapillary
Thu Jul 09 19:51:47 CEST 2015 : app.mapillary.android.service.MapillaryServerFacade  - getTokens: HTTP/1.1 200 OK
Thu Jul 09 19:51:47 CEST 2015 : app.mapillary.android.service.MapillaryServerFacade  - getHttpGet: https://a.mapillary.com/v2/me
Thu Jul 09 19:51:47 CEST 2015 : app.mapillary.android.service.MapillaryServerFacade  - projects:[]
Thu Jul 09 19:51:47 CEST 2015 : app.mapillary.android.service.MapillaryServerFacade  - sign_in jwtToken:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtcHkiLCJzdWIiOiJpTl9rWDhJQVlsNkdESVBDczdudTN3IiwiYXVkIjoiTWtKS2JEQTBiblp1WmxjeGVUSkhUbUZxTjNnMWR6bzBabVl4TjJNek1UUmxZek0xTTJFMiIsImlhdCI6MTQzNTg1NDk5MSwianRpIjoiM2EzNzhkYzkzMjRkNTM2ZTcyYTVkNDJiOWQ4MTI3YjMiLCJzY28iOlsibWFwaWxsYXJ5OnVzZXIiXSwidmVyIjoxfQ.8e-rQwTDaPrYM9nt0EmZrdfb89jAgAzQxfw9uDAgmn0, upload_token: jrtfkW_WzicwJwCsjgZMyA
Thu Jul 09 19:51:49 CEST 2015 : app.mapillary.android.activity.FeedFragment$FetchFeedTask  - got: 5 kb
```

I didn't quite understand: What's the difference between these two files?

**Comment by de-vries** [comment]
I can confirm this issue for 1.28, but in 1.29 it's gone

**Comment by peterneubauer** [comment]
Good, closing this then for the next release.

**Comment by peterneubauer** [comment]
Closing this.
