### ISSUE TITLE
Blur from edit sequence fails

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#1249]
when (right) clicking the "edit blurring" button in the sequence editor the screen does not load properly. The following error can be seen in the console:

```
Error: [$injector:unpr] http://errors.angularjs.org/1.4.0-beta.5/$injector/unpr?p0=BlurProvider%20%3C-%20Blur%20%3C-%20BCtrl
    at Error (native)
    at https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:882:423
    at https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:914:288
    at Object.d [as get] (https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:912:266)
    at https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:914:362
    at d (https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:912:266)
    at Object.e [as invoke] (https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:913:26)
    at $get.R.instance (https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:954:168)
    at M (https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:935:373)
    at h (https://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-232c5879.js:929:213) <div ui-view="">(anonymous function) @ lib-232c5879.js:981$get @ lib-232c5879.js:954aa @ lib-232c5879.js:947M @ lib-232c5879.js:936h @ lib-232c5879.js:929(anonymous function) @ lib-232c5879.js:928updateView @ lib-232c5879.js:5270(anonymous function) @ lib-232c5879.js:5232$get.l.$broadcast @ lib-232c5879.js:1009$state.transitionTo.$state.transition.resolved.then.$state.transition @ lib-232c5879.js:4622(anonymous function) @ lib-232c5879.js:992$get.l.$eval @ lib-232c5879.js:1006$get.l.$digest @ lib-232c5879.js:1003$get.l.$apply @ lib-232c5879.js:1007l @ lib-232c5879.js:959N @ lib-232c5879.js:964B.onload @ lib-232c5879.js:965
```

**Comment by knikel** [comment]
@mprins this button should redirect back to the viewer. Should be all good now. Thanks for catching that.
