### ISSUE TITLE
image browser stuck after a while

### ISSUE THREAD

**Issue by liskin** [mapillary/mapillary_issues#1467]
When I browse images either via play or by manually clicking the arrow, sooner or later the browser gets irrecoverably stuck. JS console says:

    TypeError: Cannot read property 'node' of undefined
        at checkKeyBackwards (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-68586b50.js:27565:35)
        at Object.checkDir (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-68586b50.js:27607:17)
        at LocalNavigator.moveDir (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-68586b50.js:23137:44)
        at LocalNavigator.moveDir (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-68586b50.js:22871:61)
        at Scope.$scope.move (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/mapapp-68586b50.js:14213:24)
        at fn (eval at <anonymous> (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-652d59df.js:1:0), <anonymous>:4:400)
        at callback (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-652d59df.js:23211:17)
        at Scope.$eval (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-652d59df.js:16112:28)
        at Scope.$apply (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-652d59df.js:16211:23)
        at HTMLDivElement.<anonymous> (http://d1dk9tvuiy3v51.cloudfront.net/javascripts/lib-652d59df.js:23216:23)

User agent: Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by oscarlorentzon** [comment]
Thanks for reporting this @liskin !

The issue causing the the output in the JS console you provided has now been resolved. If you still experience that the browser gets stuck it is related to something else. Please report a new issue if that is the case and I'll start a new investigation. Thanks again!
