### ISSUE TITLE
android app crash with incoming call

### ISSUE THREAD

**Issue by HolgerJeromin** [mapillary/mapillary_issues#1537]
I keep logcat installed for a while :-)
desire hd with android 4.0.4 custom firmware.
````
11-19 11:13:27.492 E/AndroidRuntime(2741): FATAL EXCEPTION: main
11-19 11:13:27.492 E/AndroidRuntime(2741): java.lang.NullPointerException
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at app.mapillary.android.activity.CameraActivity$9.onPictureTaken(CameraActivity.java:606)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at android.os.Handler.dispatchMessage(Handler.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at android.os.Looper.loop(Looper.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at android.app.ActivityThread.main(ActivityThread.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at java.lang.reflect.Method.invoke(Method.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
11-19 11:13:27.492 E/AndroidRuntime(2741): 	at dalvik.system.NativeStart.main(Native Method)
11-19 11:13:27.532 E/EmbeddedLogger(1683): App crashed! Process: app.mapillary
11-19 11:13:27.532 E/EmbeddedLogger(1683): App crashed! Package: app.mapillary v158 (1.58)
````

**Comment by HolgerJeromin** [comment]
I shot 415 images with great success in riding, manual foot and panorama mode. 
So i am very happy with the performance of the 1.58 despite giving you another crash report :-)

**Comment by HolgerJeromin** [comment]
I think this can be closed.
