### ISSUE TITLE
app crashes during review with OutOfMemoryError

### ISSUE THREAD

**Issue by roadblock2** [mapillary/mapillary_issues#1555]
Since upgrading to 1.52, the Android app crashes a lot during review, after reviewing about 30 to 50 photos. With some older version there were already similar crashes, but not that often (maybe every 200 pictures).

This is on a Samsung Galaxy S4 mini, with Android 4.4.2.
Here are some crash infos from system log:

```
11-15 19:15:14.430 D/dalvikvm(24933): GC_FOR_ALLOC freed 287K, 11% free 231144K/259112K, paused 39ms, total 40ms
11-15 19:15:14.430 I/dalvikvm-heap(24933): Forcing collection of SoftReferences for 3995152-byte allocation
11-15 19:15:14.490 D/dalvikvm(24933): GC_BEFORE_OOM freed 15K, 11% free 231129K/259112K, paused 59ms, total 59ms
11-15 19:15:14.490 E/dalvikvm-heap(24933): Out of memory on a 3995152-byte allocation.
11-15 19:15:14.490 I/dalvikvm(24933): "AsyncTask #3" prio=5 tid=20 RUNNABLE
11-15 19:15:14.490 I/dalvikvm(24933):   | group="main" sCount=0 dsCount=0 obj=0x457644e0 self=0x63bdd5d8
11-15 19:15:14.490 I/dalvikvm(24933):   | sysTid=25074 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1672695432
11-15 19:15:14.490 I/dalvikvm(24933):   | state=R schedstat=( 0 0 0 ) utm=404 stm=44 core=1
11-15 19:15:14.490 I/dalvikvm(24933):   at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
11-15 19:15:14.490 I/dalvikvm(24933):   at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:373)
11-15 19:15:14.490 I/dalvikvm(24933):   at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:75)
11-15 19:15:14.490 I/dalvikvm(24933):   at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1485)
11-15 19:15:14.490 I/dalvikvm(24933):   at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1459)
11-15 19:15:14.490 I/dalvikvm(24933):   at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-15 19:15:14.490 I/dalvikvm(24933):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-15 19:15:14.490 I/dalvikvm(24933):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-15 19:15:14.490 I/dalvikvm(24933):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-15 19:15:14.490 I/dalvikvm(24933):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-15 19:15:14.490 I/dalvikvm(24933):   at java.lang.Thread.run(Thread.java:841)
11-15 19:15:14.490 I/dalvikvm(24933): 
11-15 19:15:14.490 D/skia    (24933): --- decoder->decodeRegion returned false
11-15 19:15:14.500 D/Sensors (696): LightSensor readEvents x = 105.000000, raw = 105
11-15 19:15:14.500 W/dalvikvm(24933): threadid=20: thread exiting with uncaught exception (group=0x418fdda0)
11-15 19:15:14.500 E/AndroidRuntime(24933): FATAL EXCEPTION: AsyncTask #3
11-15 19:15:14.500 E/AndroidRuntime(24933): Process: app.mapillary, PID: 24933
11-15 19:15:14.500 E/AndroidRuntime(24933): java.lang.RuntimeException: An error occured while executing doInBackground()
11-15 19:15:14.500 E/AndroidRuntime(24933):     at android.os.AsyncTask$3.done(AsyncTask.java:300)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.lang.Thread.run(Thread.java:841)
11-15 19:15:14.500 E/AndroidRuntime(24933): Caused by: java.lang.OutOfMemoryError
11-15 19:15:14.500 E/AndroidRuntime(24933):     at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:373)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:75)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1485)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask.doInBackground(SubsamplingScaleImageView.java:1459)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
11-15 19:15:14.500 E/AndroidRuntime(24933):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-15 19:15:14.500 E/AndroidRuntime(24933):     ... 4 more
11-15 19:15:14.510 W/ActivityManager(696):   Force finishing activity app.mapillary/.android.activity.ReviewImageActivity
```

**Comment by echeloni2p** [comment]
Hi!

Do you have the thumbnails enabled?
Usually that does work fine with >1000 pictures. But if you have thumbnails disabled, the real "big ones" pictures are used to review and the OOM does happen.

echelon

**Comment by roadblock2** [comment]
@echeloni2p where do I see whether thumbnails are enabled? There is no such option in Settings tab.

In Review tab I usually see a list of thumbnails for every sequence, and then I click on one thumbnail, get the larger version, and swipe through the pictures for reviewing.

**Comment by echeloni2p** [comment]
Hi

there is a setting "generating thumbnails" in newer Mapillary Apps on Android.
But sounds like you did so and the app consumes too much memory as you do too much review on your system. Mapillary could maybe do better trash collection.

echelon

**Comment by ToeBee** [comment]
This is happening to me on a Galaxy S5. If I'm just paging through pictures it happens after 20-22 pictures every time. Thumbnails checkbox is checked.

**Comment by peterneubauer** [comment]
Closing, is fixed.
