### ISSUE TITLE
FATAL EXCEPTION in AsyncTask

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#2308]
### Basic information
* Platform: `Android 6.0`
* Version: `2.44` 
* System/Browser: `Motorola Moto G 2`

### Steps to reproduce behavior

 1. Closed mapillary
 2. Opened it again

### Expected behavior

Open

### Actual behavior

Crashed

### Additional information

In the log I can see this:

```
--------- beginning of crash
10-15 10:16:03.721 E/AndroidRuntime(27349): FATAL EXCEPTION: AsyncTask #2
10-15 10:16:03.721 E/AndroidRuntime(27349): Process: app.mapillary, PID: 27349
10-15 10:16:03.721 E/AndroidRuntime(27349): java.lang.RuntimeException: An error occurred while executing doInBackground()
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.os.AsyncTask$3.done(AsyncTask.java:309)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.lang.Thread.run(Thread.java:818)
10-15 10:16:03.721 E/AndroidRuntime(27349): Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6603)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:954)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.ViewGroup.invalidateChild(ViewGroup.java:5084)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.View.invalidateInternal(View.java:12716)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.View.invalidate(View.java:12680)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.View.invalidate(View.java:12664)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.feed.HomeFragment.displayRecyclerView(HomeFragment.java:93)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.feed.HomeFragment.onException(HomeFragment.java:135)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.rest.HttpGetTask.onException(HttpGetTask.java:153)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.rest.HttpGetTask.doInBackground(HttpGetTask.java:76)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.rest.HttpGetTask.doInBackground(HttpGetTask.java:21)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-15 10:16:03.721 E/AndroidRuntime(27349):     ... 4 more
```

**Comment by rsahlin** [comment]
Fixed, please re-test when next version is out and re-open if problem persists.

**Comment by naoliv** [comment]
With version 2.45 it's even worse (it crashes all the time).

```
--------- beginning of crash
10-15 10:16:03.721 E/AndroidRuntime(27349): FATAL EXCEPTION: AsyncTask #2
10-15 10:16:03.721 E/AndroidRuntime(27349): Process: app.mapillary, PID: 27349
10-15 10:16:03.721 E/AndroidRuntime(27349): java.lang.RuntimeException: An error occurred while executing doInBackground()
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.os.AsyncTask$3.done(AsyncTask.java:309)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.lang.Thread.run(Thread.java:818)
10-15 10:16:03.721 E/AndroidRuntime(27349): Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6603)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:954)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.ViewGroup.invalidateChild(ViewGroup.java:5084)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.View.invalidateInternal(View.java:12716)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.View.invalidate(View.java:12680)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.view.View.invalidate(View.java:12664)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.feed.HomeFragment.displayRecyclerView(HomeFragment.java:93)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.feed.HomeFragment.onException(HomeFragment.java:135)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.rest.HttpGetTask.onException(HttpGetTask.java:153)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.rest.HttpGetTask.doInBackground(HttpGetTask.java:76)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at app.mapillary.android.rest.HttpGetTask.doInBackground(HttpGetTask.java:21)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-15 10:16:03.721 E/AndroidRuntime(27349):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-15 10:16:03.721 E/AndroidRuntime(27349):     ... 4 more
```

```
10-17 18:13:03.745 E/AndroidRuntime(11316): FATAL EXCEPTION: AsyncTask #2
10-17 18:13:03.745 E/AndroidRuntime(11316): Process: app.mapillary, PID: 11316
10-17 18:13:03.745 E/AndroidRuntime(11316): java.lang.RuntimeException: An error occurred while executing doInBackground()
10-17 18:13:03.745 E/AndroidRuntime(11316):     at android.os.AsyncTask$3.done(AsyncTask.java:309)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.lang.Thread.run(Thread.java:818)
10-17 18:13:03.745 E/AndroidRuntime(11316): Caused by: java.lang.IllegalStateException: Target host must not be null, or set in parameters. scheme=null, host=null, path=https://a.mapillary.com/v2/u/naoliv?client_id=X
10-17 18:13:03.745 E/AndroidRuntime(11316):     at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:631)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:313)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:580)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:503)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:481)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at app.mapillary.android.rest.HttpGetTask.doInBackground(HttpGetTask.java:74)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at app.mapillary.android.rest.HttpGetTask.doInBackground(HttpGetTask.java:23)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-17 18:13:03.745 E/AndroidRuntime(11316):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-17 18:13:03.745 E/AndroidRuntime(11316):     ... 4 more
```

I can also see this:

```
10-17 18:13:47.795 E/FirebaseApp(12704): Firebase API initialization failure.
10-17 18:13:47.795 E/FirebaseApp(12704): java.lang.reflect.InvocationTargetException
10-17 18:13:47.795 E/FirebaseApp(12704):        at java.lang.reflect.Method.invoke(Native Method)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.FirebaseApp.zza(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.FirebaseApp.zzbu(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.app.ActivityThread.installProvider(ActivityThread.java:5174)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4769)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4709)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.os.Handler.dispatchMessage(Handler.java:102)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.os.Looper.loop(Looper.java:148)
10-17 18:13:47.795 E/FirebaseApp(12704):        at android.app.ActivityThread.main(ActivityThread.java:5443)
10-17 18:13:47.795 E/FirebaseApp(12704):        at java.lang.reflect.Method.invoke(Native Method)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
10-17 18:13:47.795 E/FirebaseApp(12704): Caused by: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/app.mapillary-1/base.apk)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.iid.zzg.zzeC(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.iid.zzg.<init>(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.iid.zzg.<init>(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.iid.zzd.zzb(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
10-17 18:13:47.795 E/FirebaseApp(12704):        ... 20 more
```

And this:
```
10-17 18:13:31.294 E/FA      (12241): Task exception on worker thread: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/app.mapillary-1/base.apk): com.google.android.gms.measurement.internal.zzt.zzEd(Unknown Source)
10-17 18:13:31.801 W/DefaultRequestDirector(12241): Authentication error: Unable to respond to any of these challenges: {}
10-17 18:13:31.801 D/app.mapillary.android.service.MapillaryServerFacade(12241): getTokensEmailPwd: HTTP/1.1 401 Unauthorized
10-17 18:13:31.802 W/System.err(12241): java.lang.Exception: Could not log in. Please check your username/password
10-17 18:13:31.802 W/System.err(12241):         at app.mapillary.android.service.MapillaryServerFacade.getTokensEmailPwd(MapillaryServerFacade.java:176)
10-17 18:13:31.802 W/System.err(12241):         at app.mapillary.android.service.MapillaryServerFacade$1.doInBackground(MapillaryServerFacade.java:74)
10-17 18:13:31.802 W/System.err(12241):         at app.mapillary.android.service.MapillaryServerFacade$1.doInBackground(MapillaryServerFacade.java:68)
10-17 18:13:31.802 W/System.err(12241):         at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-17 18:13:31.802 W/System.err(12241):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-17 18:13:31.802 W/System.err(12241):         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-17 18:13:31.802 W/System.err(12241):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-17 18:13:31.802 W/System.err(12241):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-17 18:13:31.802 W/System.err(12241):         at java.lang.Thread.run(Thread.java:818)
```
