### ISSUE TITLE
Python login API v1 endpoint 404 response

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2704]
I'm using `upload_with_preprocessing.py` to upload images to Mapillary.

However, since a few hours ago, this API endpoint:
https://a.mapillary.com/v1/u/login
returns a nginx 404 page instead of a JSON response (which you can reproduce by clicking on the link).

This API endpoint is still used in `get_upload_token()` in `uploader.py`.

When being used, the script now fail with the following stacktrace:
```
Traceback (most recent call last):
  File "./upload_with_preprocessing.py", line 147, in <module>
    upload_token = get_upload_token(MAPILLARY_EMAIL, MAPILLARY_PASSWORD)
  File "/home/uli/dev/tools/mapillary_tools/python/lib/uploader.py", line 136, in get_upload_token
    resp = json.loads(response.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by katrinhumal** [comment]
@ulikoehler I think the general answer here is that you should use the most recent API version, v3, as we're deprecating the old one(s). So please make sure your mapillary_tools are updated. But I'll let @gyllen share more detailed knowledge here since I'm not a developer myself and don't want to talk too much about the things I don't really know about :)

**Comment by ulikoehler** [comment]
@katrinhumal Just to be clear, its not really me who is using the outdated and possibly deprecated API but several scripts from the official  https://github.com/mapillary/mapillary_tools repository. So i think there are two possibilities:

1. API v1 is deprecated. Then this is a bug report about mapillary_tools using an outdated API.
2. API v1 should still work. Then this is a bug report about the API server not working properly.

**Comment by gyllen** [comment]
@ulikoehler Thanks for reporting this, we finally shutdown the v1 API yesterday. The scripts should be updated to the latest API by now.

Sorry for the inconvenience.

**Comment by kaitu** [comment]
Maybe related: the script add_mapillary_tag_from_exif.py doesn't work anymore for me. I just updated to latest version of the tools, and still no luck.

**Comment by ulikoehler** [comment]
@gyllen Thank you for fixing it this quickly. I can confirm that it works flawlessly after the newest patch.

**Comment by ybkuang** [comment]
@kaitu what are the error messages that you're getting?

**Comment by kaitu** [comment]
@ybkuang 

Traceback (most recent call last):
  File "C:\Python27\Scripts\mapillary_tools-master\python\add_mapillary_tag_from
_exif.py", line 67, in <module>
    MAPILLARY_USERNAME, MAPILLARY_EMAIL, None, upload_token, sequence_uuid)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\exifedit.py", line
 102, in create_mapillary_description
    metadata = ExifEdit(filename)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\exifedit.py", line
 164, in __init__
    self.ef = JpegFile.fromFile(filename)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 95
4, in fromFile
    return JpegFile(f, filename=filename, mode=mode)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 10
17, in __init__
    attempt = segment_class(mark, input, data, self.mode)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 81
0, in __init__
    DefaultSegment.__init__(self, marker, fd, data, mode)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 12
5, in __init__
    self.parse_data(data)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 85
6, in parse_data
    ifd = IfdThumbnail(self.e, offset, self, self.mode, tiff_data)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 42
7, in __init__
    self.ifd_handler(data)
  File "C:\Python27\Scripts\mapillary_tools-master\python\lib\pexif.py", line 78
1, in ifd_handler
    raise JpegFile.InvalidFile("Thumbnail doesn't have an offset "\
lib.pexif.InvalidFile: Thumbnail doesn't have an offset and/or size

**Comment by ybkuang** [comment]
@kaitu I opened an issue in mapillary_tools to keep track of this.
