### ISSUE TITLE
Unable to "Drag to draw an object" in tag editor

### ISSUE THREAD

**Issue by ulikoehler** [mapillary/mapillary_issues#2742]
When using the new tag editor, I'm trying to create object tags by
1. selecting a tag (e.g. "manhole") and
2. Trying to drag the tag

sometimes (randomly, but in ~30-50% of cases when I click "edit tag") the editor gets stuck showing the "Drag to draw an object" tooltip. Dragging then just moves the image, it does not create any tag.

F5-reloading the page fixes the issue. I'm using Chrome 61.0.3163.100 64 bit on Ubuntu 16.04.

I've made a screencast video illustrating the issue: https://youtu.be/gKpi3_SqtnU

**Comment by nickplesha** [comment]
@ulikoehler Thanks for reporting. Can you show the error console log output when this happens? Also, holding CTRL disables creating tags so you can pan the image, double-check to see if that's affecting you.

**Comment by ulikoehler** [comment]
@nickplesha Thanks for responding so quickly.
Unfortunately CTRL does not change anything, even when pressing and releasing CTRL clicking just translates the image around.

Here's the error log you requested (after trying to create the tag and trying CRL):
https://gist.github.com/ulikoehler/fc2561ea425fec03c41b25d0fdaf6a76
error.txt contains the chrome log when the error occured. ok.log contains the log after reloading when it worked again.

This is the part that might be interesting for you:
```
vendor.9ac77456fe22ba6ccd54.bundle.js:1 THREE.WebGLRenderer 86
    vendor.9ac77456fe22ba6ccd54.bundle.js:1 EXCEPTION: 2 errors occurred during unsubscription:
      1) TypeError: Cannot read property 'indexOf' of undefined
      2) TypeError: Cannot read property 'indexOf' of undefined
    t.handleError @ vendor.9ac77456fe22ba6ccd54.bundle.js:1
    vendor.9ac77456fe22ba6ccd54.bundle.js:1 ORIGINAL STACKTRACE:
    t.handleError @ vendor.9ac77456fe22ba6ccd54.bundle.js:1
    vendor.9ac77456fe22ba6ccd54.bundle.js:1 Error: 2 errors occurred during unsubscription:
      1) TypeError: Cannot read property 'indexOf' of undefined
      2) TypeError: Cannot read property 'indexOf' of undefined
        at e.v (polyfills.1fcaf3f040fea88ba0e6.bundle.js:1)
        at new e (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.t.unsubscribe (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.unsubscribe (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e._innerSub (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e._next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e._next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e._next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e._next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.next (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
        at e.notifyNext (vendor.9ac77456fe22ba6ccd54.bundle.js:1)
    t.handleError @ vendor.9ac77456fe22ba6ccd54.bundle.js:1
    vendor.9ac77456fe22ba6ccd54.bundle.js:1 Uncaught eerrors: (2) [TypeError: Cannot read property 'indexOf' of undefined
        at e.t.off (https://www.mapillary.com/ven…, TypeError: Cannot read property 'indexOf' of undefined
        at e.t.off (https://www.mapillary.com/ven…]message: "2 errors occurred during unsubscription:↵  1) TypeError: Cannot read property 'indexOf' of undefined↵  2) TypeError: Cannot read property 'indexOf' of undefined"name: "UnsubscriptionError"stack: "Error: 2 errors occurred during unsubscription:↵  1) TypeError: Cannot read property 'indexOf' of undefined↵  2) TypeError: Cannot read property 'indexOf' of undefined↵    at e.v (https://www.mapillary.com/polyfills.1fcaf3f040fea88ba0e6.bundle.js:1:15129)↵    at new e (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:3169124)↵    at e.t.unsubscribe (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:1392041)↵    at e.unsubscribe (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66821)↵    at e._innerSub (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:3163795)↵    at e._next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:3163705)↵    at e.next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66552)↵    at e._next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66881)↵    at e.next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66552)↵    at e.next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:1378692)↵    at e._next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66881)↵    at e.next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66552)↵    at e._next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:1986712)↵    at e.next (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:66552)↵    at e.notifyNext (https://www.mapillary.com/vendor.9ac77456fe22ba6ccd54.bundle.js:1:3164291)"__proto__: Error
```

**Comment by nickplesha** [comment]
@ulikoehler Thanks for the info, the bug should be fixed but let us know if you run into any other issues.
