### ISSUE TITLE
No handlers could be found for logger "exifread"

### ISSUE THREAD

**Issue by ligfietser** [mapillary/mapillary_issues#2749]
Since recently I can't upload any images with the Python script.
I have the following line in my batch file:
 
python d:\foto\Mapillary\scripts\python\upload_with_preprocessing.py --remove_duplicates --cutoff_time 300 --cutoff_distance 500 --auto_done %DIR% 2>log.txt

log.txt output see below. 

### Basic information
* Platform: windows 
* Version: `7` 
* System/Browser: `...`

... 

No handlers could be found for logger "exifread"
Traceback (most recent call last):
  File "d:\foto\Mapillary\scripts\python\upload_with_preprocessing.py", line 191, in <module>
    s = Sequence(path, skip_folders=skip_folders)
  File "d:\foto\Mapillary\scripts\python\lib\sequence.py", line 24, in __init__
    self.file_list = self.get_file_list(filepath, check_exif)
  File "d:\foto\Mapillary\scripts\python\lib\sequence.py", line 78, in get_file_list
    image_files = [f for f in image_files if verify_exif(f)]
  File "d:\foto\Mapillary\scripts\python\lib\exif.py", line 94, in verify_exif
    exif = EXIF(filename)
  File "d:\foto\Mapillary\scripts\python\lib\exif.py", line 121, in __init__
    self.tags = exifread.process_file(fileobj, details=details)
  File "C:\Program Files (x86)\Python27\lib\site-packages\exifread\__init__.py", line 210, in process_file
    hdr.dump_ifd(exif_off.values[0], 'EXIF', stop_tag=stop_tag)
  File "C:\Program Files (x86)\Python27\lib\site-packages\exifread\classes.py", line 239, in dump_ifd
    self.dump_ifd(values[0], ifd_info[0], tag_dict=ifd_info[1], stop_tag=stop_tag)
  File "C:\Program Files (x86)\Python27\lib\site-packages\exifread\classes.py", line 227, in dump_ifd
    printable = str(values)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u05da' in position 1: ordinal not in range(128)

**Comment by ligfietser** [comment]
I noticed the mapillary scripts were a few days older than the latest. I downloaded the latest and run my script again, now with a different error:

Traceback (most recent call last):
  File "d:\foto\Mapillary\scripts\python\upload_with_preprocessing.py",
line 13, in <module>
    from lib.exifedit import create_mapillary_description
  File "d:\foto\Mapillary\scripts\python\lib\exifedit.py", line 11, in <module>
    from PIL import Image
ImportError: No module named PIL

**Comment by gyllen** [comment]
@ybkuang Reassigning to you

@ligfietser It looks like you might have to `pip install PIL`

**Comment by ligfietser** [comment]
@gyllen I already tried it, doesnt work for me.

**Comment by gyllen** [comment]
@ligfietser Ok, Im sure @ybkuang will know whats wrong, sorry for this

**Comment by ybkuang** [comment]
@ligfietser I think it is related to exifread library. Need to check if when I am with my laptop. Will keep you updated

**Comment by parpy** [comment]
move to "mapillary_tools-master"
> pip install -r requirements.txt

**Comment by katrinhumal** [comment]
@ybkuang any updates?

**Comment by ybkuang** [comment]
@ligfietser have you also try @parpy' suggestions of running `pip install -r requirements.txt`. it could be exifread is missing.

**Comment by ligfietser** [comment]
This is the output of pip install -r requirements.txt
I'm sorry, it didnt solve my problem.  I already gave it up uploading from script and do it via the web browser.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python27\lib\runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "C:\Program Files (x86)\Python27\lib\runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "C:\Program Files (x86)\Python27\lib\runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Program Files (x86)\Python27\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "C:\Program Files (x86)\Python27\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Program Files (x86)\Python27\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "C:\Program Files (x86)\Python27\lib\site-packages\pip\__init__.py", line 9, in <module>
    from pip.log import logger
  File "C:\Program Files (x86)\Python27\lib\site-packages\pip\log.py", line 8, in <module>
    from pip import backwardcompat
  File "C:\Program Files (x86)\Python27\lib\site-packages\pip\backwardcompat\__init__.py", line 74, in <module>
    import xmlrpclib
  File "C:\Program Files (x86)\Python27\lib\xmlrpclib.py", line 147, in <module>
    import gzip
  File "C:\Program Files (x86)\Python27\lib\gzip.py", line 36, in <module>
    class GzipFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

**Comment by Alessandro-Barbieri** [comment]
I'm having this issue too

**Comment by Alessandro-Barbieri** [comment]
Installed exifread with pip as user -> same

**Comment by ybkuang** [comment]
@Alessandro-Barbieri can you also paste the errors that you are getting?

**Comment by Alessandro-Barbieri** [comment]
Only this `No handlers could be found for logger "exifread"` no crashes, all seems to work (very suspicious)

**Comment by Alessandro-Barbieri** [comment]
![screenshot_2017-11-23-09-56-33](https://user-images.githubusercontent.com/10689739/33165024-9c9c0938-d035-11e7-994d-2aef136a6b0c.png)

**Comment by gregoryng** [comment]
Hello, just stopping by as I happened to see this bug while running exifread.

I believe this might be a special case of the general symptom [listed here](http://excid3.com/blog/no-handlers-could-be-found-for-logger).

Basically exifread is making calls to the logging module, and the logging module is complaining because logging doesn't have a  root logger configured.  So in your top level script you can suppress this error message by calling logging.basicConfig, although most likely you will start seeing the warnings that exifread spews, and you'll have to handle those.

**Comment by ybkuang** [comment]
@gregoryng Thanks for the suggestions. I am moving this issue to mapillary_tools https://github.com/mapillary/mapillary_tools/issues/264 and will work on a hotfix soon.
