### ISSUE TITLE
sequence editing is broken

### ISSUE THREAD

**Issue by mprins** [mapillary/mapillary_issues#408]
Getting the following error in the Chrome console when I move an image on the map:

```
TypeError: Cannot read property 'lat' of undefined
    at Object.o.Projection.SphericalMercator.project (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:7:17420)
    at Object.o.CRS.latLngToPoint (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:7:17817)
    at o.Map.o.Class.extend.project (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:7:24497)
    at o.Map.o.Class.extend.latLngToLayerPoint (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:7:24768)
    at o.Polyline.o.Path.extend.projectLatlngs (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:9:8592)
    at o.Path.o.Class.extend.redraw (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:8:28536)
    at o.Polyline.o.Path.extend.setLatLngs (https://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:9:8868)
    at updateLine (https://dga406zepc8gy.cloudfront.net/javascripts/mapapp-702828c2.js:7064:25)
    at updateChangeSet (https://dga406zepc8gy.cloudfront.net/javascripts/mapapp-702828c2.js:7073:15)
    at Object.fn (https://dga406zepc8gy.cloudfront.net/javascripts/mapapp-702828c2.js:7098:20) lib-08c6ecbd.js:131(anonymous function) lib-08c6ecbd.js:131(anonymous function) lib-08c6ecbd.js:107k.$digest lib-08c6ecbd.js:149k.$apply lib-08c6ecbd.js:151(anonymous function) mapapp-702828c2.js:6140o.Mixin.Events.fireEvent lib-08c6ecbd.js:7o.Handler.MarkerDrag.o.Handler.extend._onDragEnd lib-08c6ecbd.js:10o.Mixin.Events.fireEvent lib-08c6ecbd.js:7o.Draggable.o.Class.extend._onUp lib-08c6ecbd.js:9t.(anonymous function).s lib-08c6ecbd.js:9
```

Also the trace is not updated and panning and loading new maptiles is broken as a result of the error

![image](https://cloud.githubusercontent.com/assets/1165786/4724520/4fcab11c-5951-11e4-83db-62518003adc9.png)

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by mprins** [comment]
editing seems to be OK, the dupes are still there, eg: prGDeINes3Te18hyYO8rzA and  CVXe2-jXYr_ZB84MSHX-yA are duplicate images
