### ISSUE TITLE
Can't show panorama pictures in web browser

### ISSUE THREAD

**Issue by neuhaus** [mapillary/mapillary_issues#414]
When filtering for panos, I click one of them (on the icon with the circular arrow) and get the following errors:

    GET http://dga406zepc8gy.cloudfront.net/javascripts/angular-route.min.js.map 404 (Not Found)

    lib-08c6ecbd.js:131 TypeError: Cannot read property 'length' of undefined
        at LocalNavigator.processData (http://dga406zepc8gy.cloudfront.net/javascripts/mapapp-111dae24.js:9079:35)
        at LocalNavigator.processData (http://dga406zepc8gy.cloudfront.net/javascripts/mapapp-111dae24.js:7996:63)
        at http://dga406zepc8gy.cloudfront.net/javascripts/mapapp-111dae24.js:9161:28
        at http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:306:303
        at F (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:139:187)
        at http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:140:350
        at k.$eval (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:151:68)
        at k.$digest (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:148:168)
        at k.$apply (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:151:398)
        at h (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:111:454)
    lib-08c6ecbd.js:131 TypeError: Cannot read property 'length' of undefined
        at http://dga406zepc8gy.cloudfront.net/javascripts/mapapp-111dae24.js:9178:29
        at http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:306:303
        at F (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:139:187)
        at http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:140:350
        at k.$eval (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:151:68)
        at k.$digest (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:148:168)
        at k.$apply (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:151:398)
        at h (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:111:454)
        at u (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:116:463)
        at XMLHttpRequest.z.onreadystatechange (http://dga406zepc8gy.cloudfront.net/javascripts/lib-08c6ecbd.js:118:24)

This is on OS X Chrome 39.0.2171.36 beta (64-bit)

**Comment by jesolem** [comment]
Is this still an issue?

**Comment by neuhaus** [comment]
I'll give it a try this weekend.

**Comment by neuhaus** [comment]
The filtering for panoramas doesn't seem to work properly. When the filter is on, I still see tracks that contain non-panorama images. Can you reproduce this?

**Comment by ybkuang** [comment]
@gyllen or @knikel can you help check the pano filter?

**Comment by neuhaus** [comment]
Never mind.

I tried it a couple of minutes ago in Firefox and Chrome and it wasn't working.

Tried it again now and it's working in both of them.

Also, the issue is apparently fixed. I'm closing it. Thanks.
