### ISSUE TITLE
Android app - Can't log in after update

### ISSUE THREAD

**Issue by kolen** [mapillary/mapillary_issues#667]
I can't login (or logout) after update from old version (don't know what version was before, updated yesterday). I was logged in in previous version and was able to upload photos. I can't find login or logout buttons. It shows "Username" instead of my username and "Couldn't refresh feed" message when trying to load almost any of screens.

![screenshot_2015-02-19-13-05-37](https://cloud.githubusercontent.com/assets/24191/6264858/cf76ee9e-b838-11e4-99b4-fe0f244ea670.png)

Clearing app data didn't help.

Logs (https://gist.github.com/kolen/322e7c44496990dc43b2) contain following exceptions:

```
02-19 12:58:40.415 D/app.mapillary.android.service.MapillaryServerFacade(22269): getTokens: HTTP/1.1 401 Unauthorized
02-19 12:58:40.422 W/System.err(22269): java.lang.Exception: Could not log in. Please check your username/password
02-19 12:58:40.422 W/System.err(22269): 	at app.mapillary.android.service.MapillaryServerFacade.getTokens(MapillaryServerFacade.java:82)
02-19 12:58:40.422 W/System.err(22269): 	at app.mapillary.android.service.MapillaryServerFacade.getAuthToken(MapillaryServerFacade.java:64)
02-19 12:58:40.446 W/System.err(22269): 	at app.mapillary.android.activity.MainActivity$2.doInBackground(MainActivity.java:173)
02-19 12:58:40.446 W/System.err(22269): 	at app.mapillary.android.activity.MainActivity$2.doInBackground(MainActivity.java:167)
02-19 12:58:40.446 W/System.err(22269): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
02-19 12:58:40.446 W/System.err(22269): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
02-19 12:58:40.446 W/System.err(22269): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
02-19 12:58:40.446 W/System.err(22269): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
02-19 12:58:40.446 W/System.err(22269): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
02-19 12:58:40.446 W/System.err(22269): 	at java.lang.Thread.run(Thread.java:841)
```

```
02-19 12:57:49.251 D/app.mapillary.android.activity.ProfileFragment(21368): got: []
02-19 12:57:49.251 W/System.err(21368): java.lang.NullPointerException
02-19 12:57:49.337 W/System.err(21368): 	at app.mapillary.android.activity.ProfileFragment$FetchSequencesTask.doInBackground(ProfileFragment.java:124)
02-19 12:57:49.337 W/System.err(21368): 	at app.mapillary.android.activity.ProfileFragment$FetchSequencesTask.doInBackground(ProfileFragment.java:112)
02-19 12:57:49.337 W/System.err(21368): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
02-19 12:57:49.337 W/System.err(21368): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
02-19 12:57:49.337 W/System.err(21368): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
02-19 12:57:49.337 W/System.err(21368): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
02-19 12:57:49.337 W/System.err(21368): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
02-19 12:57:49.337 W/System.err(21368): 	at java.lang.Thread.run(Thread.java:841)
```

/storage/emulated/0/mapillary is empty (with only .nomedia file)
```
u0_a44@maguro:/ $ ls -a /storage/emulated/0/mapillary
.nomedia
u0_a44@maguro:/ $
```

Mapillary 1.04
Android 4.3.1 Cyanogenmod 10.2.1-maguro on Galaxy Nexus

**Comment by kolen** [comment]
After uninstalling app and installing again it showed login screen. I don't know why clearing app data was not enough. But still there is problem with migration code to migrate to new version (if there's any migration).

**Comment by peterneubauer** [comment]
ok, closing this now, thanks for reporting!
