### ISSUE TITLE
Couldn't close the notification with a low level battery

### ISSUE THREAD

**Issue by naoliv** [mapillary/mapillary_issues#904]
Was using Mapillary without any issues, the battery level dropped below 10%, Mapillary properly stopped and gave a "Battery level less than 10%, not..." at the notification area.
The problem: I wasn't able to swipe this message or close it. Tried to open Mapillary and exit it multiple times and the message was there.
Then plugged in the charger and it was still there (when the charger is plugged this message should disappear).
Then left the phone charging and still nothing.
Basically I had an immortal Highlander message. The only solution was to force-close the app.

Since I opened and closed it a lot of times I don't know how useful this log is:

```
--------- beginning of main
04-04 14:38:10.574 D/app.mapillary.android.activity.CameraActivity( 8582): flashing: New sequence started
04-04 14:38:10.582 D/app.mapillary.android.activity.CameraActivity( 8582): starting new sequence
04-04 14:38:11.240 D/app.mapillary.android.activity.CameraActivity( 8582): Auto-fired shot 0
04-04 14:38:11.241 I/Choreographer( 8582): Skipped 40 frames!  The application may be doing too much work on its main thread.
04-04 14:38:11.241 D/app.mapillary.android.activity.CameraActivity( 8582): Free/Total disk: 25806MB/29712.0MB, percent: 86.8538
04-04 14:38:11.249 D/app.mapillary.camera.Animation.app.mapillary.android.activity.CameraActivity$16@23a91565( 8582): onAnimationStart: New sequence started
04-04 14:38:11.336 D/app.mapillary.android.activity.CameraActivity( 8582): takeShot Queue/Tasks: 0/0 of executor pool size 4
04-04 14:38:16.831 D/app.mapillary.android.activity.CameraActivity( 8582): Camera button pressedKeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=168135610, downTime=168135610, deviceId=-1, source=0x101 }
04-04 14:38:17.022 D/app.mapillary.android.activity.CameraActivity( 8582): Camera button pressedKeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=168135674, downTime=168135610, deviceId=-1, source=0x101 }
04-04 14:38:17.860 D/app.mapillary.android.activity.StorageUtils( 8582): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 14:38:18.439 I/Choreographer( 8582): Skipped 78 frames!  The application may be doing too much work on its main thread.
04-04 14:38:18.490 D/app.mapillary.android.activity.StorageUtils( 8582): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 15:39:00.609 D/app.mapillary.android.activity.MainActivity( 8582): Android version: 21
04-04 15:39:00.609 D/app.mapillary.android.activity.MainActivity( 8582): OS version: 3.4.42-g48d3b85
04-04 15:39:00.609 D/app.mapillary.android.activity.MainActivity( 8582): Device titan_udstv
04-04 15:39:00.610 D/app.mapillary.android.activity.MainActivity( 8582): Model XT1069
04-04 15:39:00.610 D/app.mapillary.android.activity.MainActivity( 8582): Product titan_retbr_dstv
04-04 15:39:00.611 D/app.mapillary.android.activity.MainActivity( 8582): Mapillary versionName: 1.20
04-04 15:39:00.611 D/app.mapillary.android.activity.MainActivity( 8582): Mapillary versionCode: 120
04-04 15:39:01.061 D/app.mapillary.android.activity.StorageUtils( 8582): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 15:39:01.084 D/app.mapillary.android.activity.FeedFragment$FetchFeedTask( 8582): got: []
04-04 15:39:01.085 E/app.mapillary.android.activity.FeedFragment$FetchFeedTask( 8582): doInBackground connection exception
04-04 15:39:01.216 I/Adreno-EGL( 8582): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107_msm8226_LA.BF.1.1__release_AU ()
04-04 15:39:01.216 I/Adreno-EGL( 8582): OpenGL ES Shader Compiler Version: E031.25.01.03
04-04 15:39:01.216 I/Adreno-EGL( 8582): Build Date: 10/28/14 Tue
04-04 15:39:01.216 I/Adreno-EGL( 8582): Local Branch: 
04-04 15:39:01.216 I/Adreno-EGL( 8582): Remote Branch: quic/l_LNX.LA.3.6
04-04 15:39:01.216 I/Adreno-EGL( 8582): Local Patches: NONE
04-04 15:39:01.216 I/Adreno-EGL( 8582): Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107 + cb93e16 + f50fe49 + d7c18e6 + 5b9a565 + 0f3a25d + 607156e + 75511aa + e4d16c0 + 686f3eb + 211a271 + dd281ee +  NOTHING
04-04 15:39:01.216 I/OpenGLRenderer( 8582): Initialized EGL, version 1.4
04-04 15:39:01.768 V/RenderScript( 8582): Application requested CPU execution
04-04 15:39:01.770 V/RenderScript( 8582): 0xb94c31c0 Launching thread(s), CPUs 4
04-04 15:39:22.592 D/app.mapillary.android.activity.MainActivity( 8582): Android version: 21
04-04 15:39:22.592 D/app.mapillary.android.activity.MainActivity( 8582): OS version: 3.4.42-g48d3b85
04-04 15:39:22.592 D/app.mapillary.android.activity.MainActivity( 8582): Device titan_udstv
04-04 15:39:22.592 D/app.mapillary.android.activity.MainActivity( 8582): Model XT1069
04-04 15:39:22.593 D/app.mapillary.android.activity.MainActivity( 8582): Product titan_retbr_dstv
04-04 15:39:22.594 D/app.mapillary.android.activity.MainActivity( 8582): Mapillary versionName: 1.20
04-04 15:39:22.594 D/app.mapillary.android.activity.MainActivity( 8582): Mapillary versionCode: 120
04-04 15:39:22.895 D/app.mapillary.android.activity.StorageUtils( 8582): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 15:39:22.898 D/app.mapillary.android.activity.FeedFragment$FetchFeedTask( 8582): got: []
04-04 15:39:22.898 E/app.mapillary.android.activity.FeedFragment$FetchFeedTask( 8582): doInBackground connection exception
04-04 15:39:26.203 W/OpenGLRenderer( 8582): Incorrectly called buildLayer on View: View, destroying layer...
04-04 15:39:26.325 D/app.mapillary.android.activity.ProfileFragment$FetchSequencesTask( 8582): exception Unable to resolve host "a.mapillary.com": No address associated with hostname, got: []
04-04 15:39:26.327 W/System.err( 8582): java.net.UnknownHostException: Unable to resolve host "a.mapillary.com": No address associated with hostname
04-04 15:39:26.348 W/Settings( 8582): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
04-04 15:39:26.473 W/System.err( 8582):     at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
04-04 15:39:26.473 W/System.err( 8582):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
04-04 15:39:26.473 W/System.err( 8582):     at java.net.InetAddress.getAllByName(InetAddress.java:215)
04-04 15:39:26.473 W/System.err( 8582):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
04-04 15:39:26.473 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-04 15:39:26.473 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-04 15:39:26.474 W/System.err( 8582):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:374)
04-04 15:39:26.474 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
04-04 15:39:26.474 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
04-04 15:39:26.474 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:476)
04-04 15:39:26.474 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchSequencesTask.doInBackground(ProfileFragment.java:129)
04-04 15:39:26.474 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchSequencesTask.doInBackground(ProfileFragment.java:117)
04-04 15:39:26.477 W/System.err( 8582):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:26.477 W/System.err( 8582):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:26.482 W/System.err( 8582):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:26.484 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:26.484 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:26.484 W/System.err( 8582):     at java.lang.Thread.run(Thread.java:818)
04-04 15:39:26.488 W/System.err( 8582): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
04-04 15:39:26.490 W/System.err( 8582):     at libcore.io.Posix.android_getaddrinfo(Native Method)
04-04 15:39:26.490 W/System.err( 8582):     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
04-04 15:39:26.490 W/System.err( 8582):     at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
04-04 15:39:26.490 W/System.err( 8582):     ... 17 more
04-04 15:39:26.526 D/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582): exception Unable to resolve host "a.mapillary.com": No address associated with hostname got: {}
04-04 15:39:26.527 W/System.err( 8582): java.net.UnknownHostException: Unable to resolve host "a.mapillary.com": No address associated with hostname
04-04 15:39:26.528 W/System.err( 8582):     at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
04-04 15:39:26.528 W/System.err( 8582):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
04-04 15:39:26.528 W/System.err( 8582):     at java.net.InetAddress.getAllByName(InetAddress.java:215)
04-04 15:39:26.528 W/System.err( 8582):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
04-04 15:39:26.528 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-04 15:39:26.528 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-04 15:39:26.528 W/System.err( 8582):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:374)
04-04 15:39:26.528 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
04-04 15:39:26.529 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
04-04 15:39:26.529 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:476)
04-04 15:39:26.529 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:219)
04-04 15:39:26.529 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:207)
04-04 15:39:26.529 W/System.err( 8582):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:26.529 W/System.err( 8582):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:26.529 W/System.err( 8582):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:26.529 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:26.529 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:26.529 W/System.err( 8582):     at java.lang.Thread.run(Thread.java:818)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582): exception fetching null
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582): java.net.MalformedURLException
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.net.URL.<init>(URL.java:152)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.net.URL.<init>(URL.java:125)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:253)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:207)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:26.537 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.lang.Thread.run(Thread.java:818)
04-04 15:39:26.537 W/System.err( 8582): java.net.MalformedURLException
04-04 15:39:26.539 W/System.err( 8582):     at java.net.URL.<init>(URL.java:152)
04-04 15:39:26.539 W/System.err( 8582):     at java.net.URL.<init>(URL.java:125)
04-04 15:39:26.539 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:253)
04-04 15:39:26.539 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:207)
04-04 15:39:26.539 W/System.err( 8582):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:26.539 W/System.err( 8582):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:26.539 W/System.err( 8582):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:26.539 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:26.539 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:26.539 W/System.err( 8582):     at java.lang.Thread.run(Thread.java:818)
04-04 15:39:27.272 D/app.mapillary.android.activity.ProfileFragment$FetchSequencesTask( 8582): exception Unable to resolve host "a.mapillary.com": No address associated with hostname, got: []
04-04 15:39:27.272 W/System.err( 8582): java.net.UnknownHostException: Unable to resolve host "a.mapillary.com": No address associated with hostname
04-04 15:39:27.272 W/System.err( 8582):     at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
04-04 15:39:27.272 W/System.err( 8582):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
04-04 15:39:27.273 W/System.err( 8582):     at java.net.InetAddress.getAllByName(InetAddress.java:215)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:374)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
04-04 15:39:27.273 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:476)
04-04 15:39:27.273 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchSequencesTask.doInBackground(ProfileFragment.java:129)
04-04 15:39:27.273 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchSequencesTask.doInBackground(ProfileFragment.java:117)
04-04 15:39:27.273 W/System.err( 8582):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:27.273 W/System.err( 8582):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:27.273 W/System.err( 8582):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:27.273 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:27.273 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:27.273 W/System.err( 8582):     at java.lang.Thread.run(Thread.java:818)
04-04 15:39:27.297 D/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582): exception Unable to resolve host "a.mapillary.com": No address associated with hostname got: {}
04-04 15:39:27.297 W/System.err( 8582): java.net.UnknownHostException: Unable to resolve host "a.mapillary.com": No address associated with hostname
04-04 15:39:27.298 W/System.err( 8582):     at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
04-04 15:39:27.298 W/System.err( 8582):     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
04-04 15:39:27.298 W/System.err( 8582):     at java.net.InetAddress.getAllByName(InetAddress.java:215)
04-04 15:39:27.298 W/System.err( 8582):     at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:137)
04-04 15:39:27.298 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
04-04 15:39:27.298 W/System.err( 8582):     at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
04-04 15:39:27.298 W/System.err( 8582):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:374)
04-04 15:39:27.298 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
04-04 15:39:27.298 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
04-04 15:39:27.299 W/System.err( 8582):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:476)
04-04 15:39:27.299 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:219)
04-04 15:39:27.299 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:207)
04-04 15:39:27.299 W/System.err( 8582):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:27.299 W/System.err( 8582):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:27.299 W/System.err( 8582):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:27.299 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:27.299 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:27.299 W/System.err( 8582):     at java.lang.Thread.run(Thread.java:818)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582): exception fetching null
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582): java.net.MalformedURLException
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.net.URL.<init>(URL.java:152)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.net.URL.<init>(URL.java:125)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:253)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:207)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:27.300 E/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 8582):    at java.lang.Thread.run(Thread.java:818)
04-04 15:39:27.300 W/System.err( 8582): java.net.MalformedURLException
04-04 15:39:27.300 W/System.err( 8582):     at java.net.URL.<init>(URL.java:152)
04-04 15:39:27.300 W/System.err( 8582):     at java.net.URL.<init>(URL.java:125)
04-04 15:39:27.300 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:253)
04-04 15:39:27.300 W/System.err( 8582):     at app.mapillary.android.activity.ProfileFragment$FetchProfileTask.doInBackground(ProfileFragment.java:207)
04-04 15:39:27.300 W/System.err( 8582):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-04 15:39:27.300 W/System.err( 8582):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-04 15:39:27.301 W/System.err( 8582):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-04 15:39:27.301 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-04 15:39:27.301 W/System.err( 8582):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-04 15:39:27.301 W/System.err( 8582):     at java.lang.Thread.run(Thread.java:818)
04-04 15:39:28.526 D/app.mapillary.android.activity.MainActivity( 8582): Appending log to /storage/emulated/0/mapillary.log
--------- beginning of main
04-04 15:41:24.202 D/app.mapillary.android.activity.Utils( 1173): WiFi: false, Ethernet: false
04-04 15:46:19.398 D/app.mapillary.android.activity.MainActivity( 3266): refreshing tokens
04-04 15:46:19.402 D/app.mapillary.android.service.MapillaryServerFacade( 3266): getHttpPost: https://a.mapillary.com/v2/ua/login
04-04 15:46:19.422 D/app.mapillary.android.activity.MainActivity( 3266): Android version: 21
04-04 15:46:19.422 D/app.mapillary.android.activity.MainActivity( 3266): OS version: 3.4.42-g48d3b85
04-04 15:46:19.422 D/app.mapillary.android.activity.MainActivity( 3266): Device titan_udstv
04-04 15:46:19.422 D/app.mapillary.android.activity.MainActivity( 3266): Model XT1069
04-04 15:46:19.422 D/app.mapillary.android.activity.MainActivity( 3266): Product titan_retbr_dstv
04-04 15:46:19.423 D/app.mapillary.android.activity.MainActivity( 3266): Mapillary versionName: 1.20
04-04 15:46:19.423 D/app.mapillary.android.activity.MainActivity( 3266): Mapillary versionCode: 120
04-04 15:46:19.743 D/app.mapillary.android.activity.StorageUtils( 3266): getExternalStorageDirectory: /storage/emulated/0
04-04 15:46:19.745 D/app.mapillary.android.activity.StorageUtils( 3266): Android 19+ : Context.getExternalFilesDirs(): /storage/emulated/0/Android/data/app.mapillary/files
04-04 15:46:19.745 D/app.mapillary.android.activity.StorageUtils( 3266): Android 19+ : Context.getExternalFilesDirs(): /storage/sdcard1/Android/data/app.mapillary/files
04-04 15:46:19.746 D/app.mapillary.android.activity.StorageUtils( 3266): bestPath: /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 15:46:19.746 D/app.mapillary.android.activity.StorageUtils( 3266): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 15:46:20.097 D/OpenGLRenderer( 3266): Render dirty regions requested: true
04-04 15:46:20.107 D/Atlas   ( 3266): Validating map...
04-04 15:46:20.168 I/Adreno-EGL( 3266): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107_msm8226_LA.BF.1.1__release_AU ()
04-04 15:46:20.168 I/Adreno-EGL( 3266): OpenGL ES Shader Compiler Version: E031.25.01.03
04-04 15:46:20.168 I/Adreno-EGL( 3266): Build Date: 10/28/14 Tue
04-04 15:46:20.168 I/Adreno-EGL( 3266): Local Branch: 
04-04 15:46:20.168 I/Adreno-EGL( 3266): Remote Branch: quic/l_LNX.LA.3.6
04-04 15:46:20.168 I/Adreno-EGL( 3266): Local Patches: NONE
04-04 15:46:20.168 I/Adreno-EGL( 3266): Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.04.04.02.162.107 + cb93e16 + f50fe49 + d7c18e6 + 5b9a565 + 0f3a25d + 607156e + 75511aa + e4d16c0 + 686f3eb + 211a271 + dd281ee +  NOTHING
04-04 15:46:20.169 I/OpenGLRenderer( 3266): Initialized EGL, version 1.4
04-04 15:46:20.184 D/OpenGLRenderer( 3266): Enabling debug mode 0
04-04 15:46:21.530 D/app.mapillary.android.service.MapillaryServerFacade( 3266): getTokens: HTTP/1.1 200 OK
04-04 15:46:21.531 D/app.mapillary.android.service.MapillaryServerFacade( 3266): getHttpGet: https://a.mapillary.com/v2/me
04-04 15:46:21.931 W/OpenGLRenderer( 3266): Incorrectly called buildLayer on View: View, destroying layer...
04-04 15:46:22.002 W/Settings( 3266): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
--------- beginning of system
04-04 15:46:22.185 W/ResourcesManager( 3266): Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
04-04 15:46:22.185 W/ResourcesManager( 3266): Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
04-04 15:46:22.226 E/art     ( 3266): dlopen("/data/app/app.mapillary-1/lib/arm/libgmscore.so", RTLD_LAZY) failed: dlopen failed: library "/data/app/app.mapillary-1/lib/arm/libgmscore.so" not found
04-04 15:46:22.226 E/ProviderInstaller( 3266): Unable to load native code from /data/app/app.mapillary-1/lib/arm/libgmscore.so
04-04 15:46:22.229 I/art     ( 3266): Background sticky concurrent mark sweep GC freed 2596(159KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 22MB/22MB, paused 6.294ms total 25.491ms
04-04 15:46:22.247 E/ProviderInstaller( 3266): libgmscore version mismatch (0 vs. 7099)
04-04 15:46:22.256 I/art     ( 3266): Background sticky concurrent mark sweep GC freed 85(5KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 22MB/22MB, paused 7.864ms total 24.395ms
04-04 15:46:22.342 I/art     ( 3266): Background partial concurrent mark sweep GC freed 4289(184KB) AllocSpace objects, 2(4MB) LOS objects, 39% free, 17MB/29MB, paused 12.034ms total 84.412ms
04-04 15:46:22.908 D/app.mapillary.android.service.MapillaryServerFacade( 3266): projects:[]
04-04 15:46:24.595 D/app.mapillary.android.activity.FeedFragment$FetchFeedTask( 3266): got: 6 kb
04-04 15:46:25.987 D/app.mapillary.android.activity.MainActivity( 3266): Android version: 21
04-04 15:46:25.987 D/app.mapillary.android.activity.MainActivity( 3266): OS version: 3.4.42-g48d3b85
04-04 15:46:25.987 D/app.mapillary.android.activity.MainActivity( 3266): Device titan_udstv
04-04 15:46:25.987 D/app.mapillary.android.activity.MainActivity( 3266): Model XT1069
04-04 15:46:25.987 D/app.mapillary.android.activity.MainActivity( 3266): Product titan_retbr_dstv
04-04 15:46:25.988 D/app.mapillary.android.activity.MainActivity( 3266): Mapillary versionName: 1.20
04-04 15:46:25.988 D/app.mapillary.android.activity.MainActivity( 3266): Mapillary versionCode: 120
04-04 15:46:26.220 D/app.mapillary.android.activity.StorageUtils( 3266): getDefaultImageStoragePath- /storage/sdcard1/Android/data/app.mapillary/files/mapillary
04-04 15:46:27.158 D/app.mapillary.android.activity.ProfileFragment$FetchSequencesTask( 3266): got: 10 kb
04-04 15:46:28.486 D/app.mapillary.android.activity.ProfileFragment$FetchProfileTask( 3266): got: 0 kb
```

**Comment by peterneubauer** [comment]
Thanks, sounds like a bug.

**Comment by naoliv** [comment]
I don't know if this can be related with #903, since it happened after the problem with the pictures.
Maybe some thread/process from the previous problem was still running? (and thus I wasn't able to close the notification?)

**Comment by iav** [comment]
like #863?

**Comment by naoliv** [comment]
Similar to the first part of #863 indeed

**Comment by polarbearing** [comment]
Confirming the bug, using 1.29

**Comment by polarbearing** [comment]
Still present in 1.43.

**Comment by ovivoda** [comment]
This issue should be fixed in the latest app version
